### ISSUE TITLE
Dependency on color-name causes CommonJS build to fail on Webpack

### ISSUE THREAD

**Issue by gaearon** [MoOx/color-string#20]
I tried using `color` but it looks like `color-string` depends on `color-name` whose entry point is a JSON file.

It seems that Webpack does not resolve JSON files by default, and this rules out me using `color` as a dependency, as I can't ask consumers to opt into resolving JSON in their Webpack configs.

Feel free to close if you feel this is Webpack's issue.

**Comment by Qix-** [comment]
Go ahead an open a tick up over at [`dfcreative/color-name`](/dfcreative/color-name) about this. While their use of an `index.json` isn't *wrong*, it's uncommon. I think just throwing in an `index.js` that does `module.exports = require('./index.json');` should work.

**Comment by MoOx** [comment]
Requiring a js file that require a json won't fix the webpack issue (yeah that's more a webpack issue - seriously why webpack isn't handling json by default... @sokra why?)

I see multiple workarounds:
- the simplest way to "fix" that issue is to make a PR color-name in order to change for a js file directly, no more json
- we could make a PR to color-name to build a js file from the json in prepublish hook
- or... you can ask your users to use json-loader _if they are consuming your package with webpack_. Seriously I think 99% of webpack users are using json-loader
```js
// npm i -D json-loader
module.exports = {
  modules: {
    loaders: {
      json: "json-loader",
    }
  }
}
```
I just asked this on twitter we will see if we get some negative answers https://twitter.com/MoOx/status/647133592884248578

**Comment by Qix-** [comment]
@MoOx what about `module.exports = JSON.parse(require('fs').readFileSync(require('path').join(__dirname, 'index.json')));`?

**Comment by MoOx** [comment]
Not sure if that a good idea to use fs (especially since webpack in mainly used on client side...)

**Comment by Qix-** [comment]
Ah okay. That's me not knowing entirely what webpack it; was just an idea. Should be a webpack issue then.

**Comment by gaearon** [comment]
From my understanding it is not planned in Webpack: https://github.com/webpack/webpack/issues/184#issuecomment-36607967
I'll file an issue with `color-name` and see what the folks there think.
